### ISSUE TITLE
Problem with includes option in plugin configuration

### ISSUE THREAD

**Issue by jkbhu85** [heroku/heroku-jvm-application-deployer#85]
Consider the below configuration with `includes` option.
```xml
<configuration>
	<appName>xyz</appName>
	<includeTarget>false</includeTarget>
	<includes>
		<include>target/*.jar</include>
		<include>system.properties</include>
		<include>Procfile</include>
	</includes>
</configuration>
```

The problem is whenever I am using `includes` option and using an `*` in an `include` then I am seeing below error message:
```
[ERROR] Failed to execute goal com.heroku.sdk:heroku-maven-plugin:3.0.4:deploy (default-cli) on project ram-api: Execution default-cli of goal com.heroku
.sdk:heroku-maven-plugin:3.0.4:deploy failed: Unexpected internal error near index 1
[ERROR] \
```

I looked in to the code and found that the method `resolveIncludePattern` in the class `AbstractHerokuDeployMojo` is using the code `String[] dirs = includePattern.split(File.separator);` to split the path.

There are two problems with this code.
1. File.separator is causing the error that I mentioned above.
2. Even if it worked, this code means, in my POM the path in windows should contain `\` and the path in unix type system should contain `/`. So the path containing `/` would work in unix type system but would not work on windows system.

Also, I've not seen anyone using `\` as path separator in pom files. I recommend that you use `/` as path separator which will solve both issues.

To reproduce the error just execute below Java code snippet on a windows machine.

```java
"abc/*.jar".split(File.separator)
```

**Comment by Malax** [comment]
Closing since there was a major update of the project since this issue was created. If this is still relevant with the current version, feel free to re-open this issue!
